#CrossCraft server properties
#1779392981
server-name=CrossCraft Server [LOCAL TEST]
motd=A CrossCraft Server
port=25565
public=true
verify-names=false
max-players=16
max-connections=3
enable-random-ticks=true
level-width=256
